export const SET_ALL_NEWS="SET_ALL_NEWS";
export const SET_NEWS_TITLE="SET_NEWS_TITLE";
export const SET_NEWS_IMAGE="SET_NEWS_IMAGE";
export const SET_NEWS_DESCRIPTION="SET_NEWS_DESCRIPTION";
export const SET_NEWS_DATE="SET_NEWS_DATE";